apiVersion: apps/v1
kind: Deployment
metadata:
  name: guaranteed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guaranteed
  template:
    metadata:
      labels:
        app: guaranteed
    spec:
      containers:
      - name: ubuntu-1
        image: ubuntu
        command: ["sh", "-c"]
        args:
          - "sleep 3600"
        resources: # 'guaranteed' qos class
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "100m"
      - name: ubuntu-2
        image: ubuntu
        command: ["sh", "-c"]
        args:
          - "sleep 3600"
        resources: # 'guaranteed' qos class
          requests:
            memory: "150Mi"
            cpu: "200m"
          limits:
            memory: "150Mi"
            cpu: "200m"
