apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: pod-with-pvc
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources: {}
    volumeMounts:
    - mountPath: /shared
      name: pvc-storage
  - image: busybox
    name: busybox2
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    resources: {}
    volumeMounts:
    - mountPath: /shared
      name: pvc-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: pvc

status: {}