apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command: ["sh", "-c"]
        args:
          - "sleep 3600"
        resources: {}
        envFrom:
        - secretRef:
            name: db-secret
        volumeMounts:
          - mountPath: /db-secret
            readOnly: true
            name: db-secret-volume
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-secret


status: {}